#Database info
host: localhost
user: test  #EDIT ME
password: '12345678' #EDIT ME
database: USER

#Adafruit info
IO_USERNAME: username #EDITME
IO_KEY: key #EDITME
feed: 
  input:
    - bk-iot-magnetic
  output:
    - bk-iot-speaker
